[package]
name = "serve"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.5" }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
serde = { version = "1.0", features = ["derive"] }
